# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lptcc-peek-reader

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://lptccapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6d603e261dbc4ff7a5ddf2ed9501d8dd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f80e015e1e8f433da685f1b552083d4f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: lptccapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6d603e261dbc4ff7a5ddf2ed9501d8dd }}/lptccapi/lptccapi/peekreaderserviceapi:${{ github.sha }}
        file: ./PeekReaderService/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lptcc-peek-reader'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_42fe44febabd4a3bb25faa127a2a6ff0 }}
        images: 'lptccapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6d603e261dbc4ff7a5ddf2ed9501d8dd }}/lptccapi/lptccapi/peekreaderserviceapi:${{ github.sha }}'